table OrderLines
	lineageTag: 8b9c0d1e-2f3a-4b5c-6d7e-8f9a0b1c2d3e

	column OrderLineID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 9c0d1e2f-3a4b-5c6d-7e8f-9a0b1c2d3e4f
		summarizeBy: none
		sourceColumn: OrderLineID

		annotation SummarizationSetBy = Automatic

	column OrderID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 0d1e2f3a-4b5c-6d7e-8f9a-0b1c2d3e4f5a
		summarizeBy: none
		sourceColumn: OrderID

		annotation SummarizationSetBy = Automatic

	column StockItemID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 1e2f3a4b-5c6d-7e8f-9a0b-1c2d3e4f5a6b
		summarizeBy: none
		sourceColumn: StockItemID

		annotation SummarizationSetBy = Automatic

	column Description
		dataType: string
		lineageTag: 2f3a4b5c-6d7e-8f9a-0b1c-2d3e4f5a6b7c
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 3a4b5c6d-7e8f-9a0b-1c2d-3e4f5a6b7c8d
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column UnitPrice
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 4b5c6d7e-8f9a-0b1c-2d3e-4f5a6b7c8d9e
		summarizeBy: sum
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

	column TaxRate
		dataType: decimal
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 5c6d7e8f-9a0b-1c2d-3e4f-5a6b7c8d9e0f
		summarizeBy: none
		sourceColumn: TaxRate

		annotation SummarizationSetBy = Automatic

	column PickedQuantity
		dataType: int64
		formatString: 0
		lineageTag: 6d7e8f9a-0b1c-2d3e-4f5a-6b7c8d9e0f1a
		summarizeBy: sum
		sourceColumn: PickedQuantity

		annotation SummarizationSetBy = Automatic

	partition OrderLines = m
		mode: import
		source =
				let
				    Source = Sql.Database("sql1.orb.local,1433", "WideWorldImporters-Full"),
				    Sales_OrderLines = Source{[Schema="Sales",Item="OrderLines"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(Sales_OrderLines,{"PackageTypeID", "PickingCompletedWhen", "LastEditedBy", "LastEditedWhen"})
				in
				    #"Removed Columns"

		annotation PBI_ResultType = Table

