table StockItems
	lineageTag: 7a8b9c0d-1e2f-3a4b-5c6d-7e8f9a0b1c2d

	column StockItemID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 8b9c0d1e-2f3a-4b5c-6d7e-8f9a0b1c2d3e
		summarizeBy: none
		sourceColumn: StockItemID

		annotation SummarizationSetBy = Automatic

	column StockItemName
		dataType: string
		lineageTag: 9c0d1e2f-3a4b-5c6d-7e8f-9a0b1c2d3e4f
		summarizeBy: none
		sourceColumn: StockItemName

		annotation SummarizationSetBy = Automatic

	column Brand
		dataType: string
		lineageTag: 0d1e2f3a-4b5c-6d7e-8f9a-0b1c2d3e4f5a
		summarizeBy: none
		sourceColumn: Brand

		annotation SummarizationSetBy = Automatic

	column Size
		dataType: string
		lineageTag: 1e2f3a4b-5c6d-7e8f-9a0b-1c2d3e4f5a6b
		summarizeBy: none
		sourceColumn: Size

		annotation SummarizationSetBy = Automatic

	column UnitPrice
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 2f3a4b5c-6d7e-8f9a-0b1c-2d3e4f5a6b7c
		summarizeBy: sum
		sourceColumn: UnitPrice

		annotation SummarizationSetBy = Automatic

	column RecommendedRetailPrice
		dataType: decimal
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 3a4b5c6d-7e8f-9a0b-1c2d-3e4f5a6b7c8d
		summarizeBy: sum
		sourceColumn: RecommendedRetailPrice

		annotation SummarizationSetBy = Automatic

	column IsChillerStock
		dataType: boolean
		formatString: "TRUE";"TRUE";"FALSE"
		lineageTag: 4b5c6d7e-8f9a-0b1c-2d3e-4f5a6b7c8d9e
		summarizeBy: none
		sourceColumn: IsChillerStock

		annotation SummarizationSetBy = Automatic

	partition StockItems = m
		mode: import
		source =
				let
				    Source = Sql.Database("sql1.orb.local,1433", "WideWorldImporters-Full"),
				    Warehouse_StockItems = Source{[Schema="Warehouse",Item="StockItems"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(Warehouse_StockItems,{"SupplierID", "ColorID", "UnitPackageID", "OuterPackageID", "LeadTimeDays", "QuantityPerOuter", "Barcode", "TaxRate", "TypicalWeightPerUnit", "MarketingComments", "InternalComments", "Photo", "CustomFields", "Tags", "SearchDetails", "LastEditedBy", "ValidFrom", "ValidTo"})
				in
				    #"Removed Columns"

		annotation PBI_ResultType = Table

